auth0/SimpleKeychain

SimpleKeychain.xcodeproj/project.pbxproj, SimpleKeychain/A0SimpleKeychain.m
=> Avoid memory leak for access control

SimpleKeychain/A0SimpleKeychain.m
As discussed in comments on 71784e3
=> Only show ios7 error message when attempting to use access control

SimpleKeychain/A0SimpleKeychain.m
=> Update default accessibility

SimpleKeychain.xcodeproj/project.pbxproj, SimpleKeychain/A0SimpleKeychain+KeyPair.h, SimpleKeychain/A0SimpleKeychain.h, SimpleKeychain/A0SimpleKeychain.m
- Deprecate -publicRSAKeyDataForTag:
- Use kSecUseAuthenticationUI instead of kSecUseAuthenticationUIFail
=> Fix Xcode warnings

README.md
Fixes formatting and upgrades a few http:// reference to https://
=> Minor fixes for README

CHANGELOG.md, README.md, SimpleKeychain/Info.plist, SimpleKeychainApp/Info.plist, SimpleKeychainTests/Info.plist, fastlane/README.md
**Added**
- Swift Package Manager support [\#75](https://github.com/auth0/SimpleKeychain/pull/75) ([StuClift](https://github.com/StuClift))
**Changed**
- Reused LocalAuthentication context [\#74](https://github.com/auth0/SimpleKeychain/pull/74) ([eaceto](https://github.com/eaceto))
=> Release 0.10.0 [SDK-1343]

CHANGELOG.md, README.md, SimpleKeychain/Info.plist, SimpleKeychainApp/Info.plist, SimpleKeychainTests/Info.plist, fastlane/README.md, tvOSTestHost/Info.plist
**Changed**
- Updated Quick and Nimble [\#97](https://github.com/auth0/SimpleKeychain/pull/97) ([Widcket](https://github.com/Widcket))
=> Release 0.12.0

README.md
- Added documentation for removing all entries to the readme
Please include relevant links supporting this change such as a:
- support ticket
- community post
- StackOverflow post
- support forum thread
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If helpful, please include manual testing steps as well.
=> Add documentation for removing all entries

V1_MIGRATION_GUIDE.md
This PR adds the placeholder migration guide that will be progressively filled in.
=> Add migration guide [SDK-3393]

.gitignore, .swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
This PR adds the `.swiftpm` directory to the gitignore file, and deletes its contents.
=> Add `.swiftpm` directory to `.gitignore`

README.md
This PR adds the support policy for Xcode, Swift and platform versions to the README.
=> Add support policy [SDK-3420]

SimpleKeychain.xcodeproj/project.pbxproj, SimpleKeychain/Accessibility.swift, SimpleKeychain/SimpleKeychain.swift, SimpleKeychain/SimpleKeychainError.swift, SimpleKeychainTests/AccessibilitySpec.swift, SimpleKeychainTests/SimpleKeychainErrorSpec.swift, SimpleKeychainTests/SimpleKeychainSpec.swift
This PR adds missing unit tests. The coverage is now at 100%.
[X] This change adds unit test coverage (or why not)
[X] This change has been tested on the latest version of the platform/language or why not
=> Add missing unit tests

SimpleKeychain/SimpleKeychain.swift, SimpleKeychainTests/SimpleKeychainSpec.swift
This PR adds unit tests for each query, and removes some unit tests that became redundant.
=> Add unit tests for queries

.github/ISSUE_TEMPLATE/Bug Report.yml, .github/ISSUE_TEMPLATE/Feature Request.yml
This PR adds a couple of placeholders to issue form fields.
=> Add placeholders to issue forms

README.md
This PR updates the README by removing all references to the "First Availability" stage.
=> Update README for GA [SDK-3500]

.github/ISSUE_TEMPLATE/Bug Report.yml, .github/ISSUE_TEMPLATE/Feature Request.yml, .github/PULL_REQUEST_TEMPLATE.md, CONTRIBUTING.md, EXAMPLES.md, README.md
This PR incorporates the redesigned README, splitting the most advances use cases off into EXAMPLES.md. The issue templates and CONTRIBUTING.md have been updated accordingly.
=> Add the redesigned README [SDK-3711]

CONTRIBUTING.md, EXAMPLES.md, README.md
This PR replaces the existing callouts in all the Markdown docs with the new GitHub-supported [admonitions](https://github.com/orgs/community/discussions/16925).
=> Use the new GitHub admonitions

Gemfile.lock
PR bumping Gemfile.lock to resolve Snyk warnings.
=> chore: Update Gemfile dependencies 

.github/actions/setup/action.yml, .github/actions/test/action.yml, .github/workflows/main.yml, SimpleKeychain.xcodeproj/project.pbxproj
This PR adds a workflow for running all CI checks using GitHub Actions. The CircleCI configuration will be removed in a follow-up PR.
=> Add GitHub Actions workflow [SDK-4458]

.github/actions/test/action.yml, .github/workflows/main.yml
- Use a concurrency group to cancel previous runs when pushing successive commits to a PR
- Pin the version of a couple actions that were not pinned to a SHA
- Remove "Cancel wokflow on failure" step as that requires additional permissions
- Simplify Carthage cache steps
=> Improve GH Actions workflows
