auth0/SimpleKeychain

Pod/Classes/A0SimpleKeychain.h
Pod/Classes/A0SimpleKeychain.m

Added overload for dataForKey: that returns an error code to the caller.
The main reason is to determine the cause for a nil return value in a TouchId situation.
Did the method return nil because the key really was not found, or did the user simply
fail to authenticate or cancel the authentication request.

TouchId: Determine reason for failed dataForKey: call

---

Pod/Classes/A0SimpleKeychain.m

Init the ``string`` variable in stringForKey to prevent compiler errors with ``-Wsometimes-uninitialised``.
As it currently is, compilation in my project fails like so:
```
A0SimpleKeychain.m:62:9: error: variable 'string' is used uninitialized whenever 'if' condition is false [-Werror,-Wsometimes-uninitialized]
if (data) {
^~~~
A0SimpleKeychain.m:65:12: note: uninitialized use occurs here
return string;
^~~~~~
A0SimpleKeychain.m:62:5: note: remove the 'if' if its condition is always true
if (data) {
^~~~~~~~~~
A0SimpleKeychain.m:61:21: note: initialize the variable 'string' to silence this warning
NSString *string;
^
= nil
1 error generated.
```
This PR implements the given suggestion, allowing my project to compile.

Initialise variable in stringForKey

---

SimpleKeychain/A0SimpleKeychain.m

SecItem.h
extern const CFStringRef kSecUseOperationPrompt
__OSX_AVAILABLE_STARTING(__MAC_10_10, __IPHONE_8_0);

Avoid iOS7 kSecUseOperationPrompt crash

---

.circleci/config.yml
.gitignore
Package.swift
SimpleKeychain.podspec
SimpleKeychain/include/A0SimpleKeychain+KeyPair.h
SimpleKeychain/include/A0SimpleKeychain.h

Adds support for building this package with the swift package manager.
Swift Package Manager is very opinionated about the file structure for packages, so in order to minimise the diff for this PR I have tried to keep the existing structure in place. There is an additional `include` folder containing the required headers symlinked in order to generate the umbrella header.
I have hopefully excluded this from the pod spec properly.
Adds support requested in #71 
Opens the path to https://github.com/auth0/Auth0.swift/issues/306
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If helpful, please include manual testing steps as well. 
[x] This change adds unit test coverage (or why not)
I have added a step the the Circle CI config to …

Swift package manager support

---

SimpleKeychain/A0SimpleKeychain.h
SimpleKeychain/A0SimpleKeychain.m

Please describe both what is changing and why this is important. Include:
- Added an instance of LAContext to the Keychain class in order to reuse it.
- Expose the LAContext as a read property in order to reuse it outside of the Keychain (In Auth0's CredentialManager, for example)
Please include relevant links supporting this change such as a:
- fix issue: https://github.com/auth0/SimpleKeychain/issues/73 
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If helpful, please include manual testing steps as well. 
1. Create an instance of Keychain and configure it to use LocalAuthentication an access when the device is unlocked
```swift
keychain = A0SimpleKeychain()
keychain.useAccessControl = true
keychain.defaultAccessiblity = …
```

Reuse LocalAuthentication context

---

README.md
SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychain-iOS.xcscheme

- Enabled the generation of code coverage report (for the iOS target only)

Generate code coverage report [SDK-1344]

---

SimpleKeychain.xcodeproj/project.pbxproj
tvOSTestHost/AppDelegate.swift
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Back.imagestacklayer/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Front.imagestacklayer/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon - App Store.imagestack/Middle.imagestacklayer/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Content.imageset/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Back.imagestacklayer/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Content.imageset/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Front.imagestacklayer/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Content.imageset/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/App Icon.imagestack/Middle.imagestacklayer/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image Wide.imageset/Contents.json
tvOSTestHost/Assets.xcassets/App Icon & Top Shelf Image.brandassets/Top Shelf Image.imageset/Contents.json
tvOSTestHost/Assets.xcassets/Contents.json
tvOSTestHost/Base.lproj/LaunchScreen.storyboard
tvOSTestHost/Base.lproj/Main.storyboard
tvOSTestHost/Info.plist
tvOSTestHost/ViewController.swift
tvOSTestHost/tvOSTestHost.entitlements

The tvOS tests were failing because of a [missing entitlement](https://developer.apple.com/documentation/bundleresources/entitlements/keychain-access-groups), which is required on tvOS 9+. This PR adds a test host app equipped with the Keychain entitlement, to run the tvOS tests in.
[X] This change has been tested on the latest version of the platform/language or why not

Fixed tvOS tests

---

SimpleKeychain/A0SimpleKeychain+KeyPair.h

- Declare `-[A0SimpleKeychain keyRefOfRSAKeyWithTag:]` and `-[A0SimpleKeychain publicRSAKeyDataForTag:]` as having nullable return types to match their implementations.
It seems like it should be valid to ask for a key that does not exist, and the implementations of these functions gracefully return `null` in this scenario.
- [-[A0SimpleKeychain keyRefOfRSAKeyWithTag:]](https://github.com/auth0/SimpleKeychain/blob/master/SimpleKeychain/A0SimpleKeychain%2BKeyPair.m#L120)
- [-[A0SimpleKeychain publicRSAKeyDataForTag:]](https://github.com/auth0/SimpleKeychain/blob/master/SimpleKeychain/A0SimpleKeychain%2BKeyPair.m#L72)
Closes #85.
This is a compile-time change only, though it will have an impact on source compatibility.

Mark up A0SimpleKeychain+KeyPair to admit that keys may not exist

---

CHANGELOG.md
README.md
SimpleKeychain/Info.plist
SimpleKeychainApp/Info.plist
SimpleKeychainTests/Info.plist
tvOSTestHost/Info.plist

**Changed**
- Marked up A0SimpleKeychain+KeyPair to admit that keys may not exist [\#86](https://github.com/auth0/SimpleKeychain/pull/86) ([cysp](https://github.com/cysp))
**Fixed**
- Fixed A0LocalAuthenticationCapable macro [\#81](https://github.com/auth0/SimpleKeychain/pull/81) ([Widcket](https://github.com/Widcket))

Release 0.11.0

---

SimpleKeychain/A0SimpleKeychain.m

The iOS 13.4 simulator seems to have introduced a bug in the behavior of `SecItemCopyMatching` when a `LAContext` instance is used in the query.
Using any key will result in a successful `OSCode`:
```swift
let laContext = LAContext()
let loadQuery = [
kSecClass as String: kSecClassGenericPassword,
kSecAttrService as String: UUID().uuidString,
kSecUseAuthenticationContext as String: laContext // 👈🏻
] as [String : Any]
let result = SecItemCopyMatching(loadQuery as CFDictionary, nil)
print("Result: \(result == errSecSuccess)")
// Result: true
```
And no data will actually be retrieved:
```swift
let laContext = LAContext()
let key = "foo"
let saveQuery = [
kSecClass as String: kSecClassGenericPassword,
kSecAttrService as String: key,
kSecValueData as String: "bar".data(using: .utf8)!, …
```

Disabled LAContext attribute in simulator [SDK-1476]

---

CHANGELOG.md
SimpleKeychain/Info.plist
SimpleKeychainApp/Info.plist
SimpleKeychainTests/Info.plist
tvOSTestHost/Info.plist

**Fixed**
- Disabled LAContext attribute in simulator [SDK-1476] [\#91](https://github.com/auth0/SimpleKeychain/pull/91) ([Widcket](https://github.com/Widcket))
[SDK-1476]: https://auth0team.atlassian.net/browse/SDK-1476

Release 0.11.1

---

SimpleKeychain/A0SimpleKeychain.h

On macOS Big Sur, the version number for macOS 10.12 is no longer `101200` but `1020`. This PR replaces the hardcoded number with a macro so it always resolves to the right number.
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If helpful, please include manual testing steps as well. 
[X] This change has been tested on the latest version of the platform/language or why not
[X] All existing and new tests complete …

Fixed macOS version check on Big Sur

---

README.md

Having that badge in the README does not really make sense anymore. It was removed from Auth0.swift's README as well.

Removed Carthage Compatible badge

---

README.md

This PR removes the FOSSA badge and the SVG widget from the README.
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If helpful, please include manual testing steps as well. 

Removed FOSSA badge and widget

---

SimpleKeychain/A0SimpleKeychain.m

- **kSecAttrAccessibleAlways** and **kSecAttrAccessibleAlwaysThisDeviceOnly** are deprecated on Mac Catalyst due to the fact that does not provide a useful level of protection.  They should be replaced with **kSecAttrAccessibleAfterFirstUnlock** and **kSecAttrAccessibleAfterFirstUnlockThisDeviceOnly** respectively
- https://developer.apple.com/documentation/security/ksecattraccessiblealwaysthisdeviceonly
- https://developer.apple.com/documentation/security/ksecattraccessiblealways
[X] Tested on a Mac Catalyst application, this removed the warnings sent by the compiler and still provides a secure storage.
[X] I have read the [Auth0 Code of …

Strengthen security and remove deprecations on Mac Catalyst

---

Package.swift

SimpleKeychain relies on the [Quick](https://github.com/Quick/Quick) and [Nimble](https://github.com/Quick/Nimble) test libraries for its tests, and it's pinning their version range to a particular major. Currently, when installing SimpleKeychain with the Swift Package Manager it will resolve both test dependencies even though they're not used in the actual library. This opens up the possibility of conflict if the app the libraries are imported into is using another major version of Quick/Nimble.
SPM has, since swift 5.2 (released with Xcode 11.4), supported [a way](https://github.com/apple/swift-evolution/blob/master/proposals/0226-package-manager-target-based-dep-resolution.md) to have the test dependencies not resolve if they're not used. Since we already dropped support for Xcode < …

Make test dependencies not resolve when installing with SPM [SDK-2598]

---

CHANGELOG.md
SimpleKeychain/Info.plist
SimpleKeychainApp/Info.plist
SimpleKeychainTests/Info.plist
tvOSTestHost/Info.plist

**Changed**
- Make test dependencies not resolve when installing with SPM [SDK-2598] [\#108](https://github.com/auth0/SimpleKeychain/pull/108) ([Widcket](https://github.com/Widcket))
[SDK-2598]: https://auth0team.atlassian.net/browse/SDK-2598

Release 0.12.3

---

.circleci/config.yml
.shiprc
SimpleKeychainApp/Info.plist
SimpleKeychainTests/Info.plist
fastlane/Fastfile
tvOSTestHost/Info.plist

This PR adds support for the new release automation CLI.
Previously, we were using a [custom Fastlane plugin](https://github.com/auth0/fastlane-plugin-auth0_shipper) for bumping the version number and updating the Changelog. To bump the version, that plugin [uses](https://github.com/auth0/fastlane-plugin-auth0_shipper/blob/master/lib/fastlane/plugin/auth0_shipper/actions/prepare_release_action.rb#L24) the `IncrementVersionNumberAction` action from Fastlane. That action [uses](https://github.com/fastlane/fastlane/blob/master/fastlane/lib/fastlane/actions/increment_version_number.rb#L71) the `agvtool new-marketing-version` command to bump the version number. That command will bump the version number in every `Info.plist` file it can find, regardless of whether it's actually necessary or …

Use the new release automation solution

---

.shiprc
SimpleKeychain.podspec
fastlane/README.md

The podspec relied on `agvtool` to get the current version number. That tool looks up the relevant key in every `Info.plist` file it can find:
This PR does away with `agvtool` and just uses the release CLI to bump the version number in the podspec. 
Related to https://github.com/auth0/SimpleKeychain/pull/112

Remove agvtool from podspec

---

.swiftpm/xcode/package.xcworkspace/contents.xcworkspacedata
Cartfile.private
Cartfile.resolved
Package.swift
SimpleKeychain/A0SimpleKeychain.m

This PR updates [Quick](https://github.com/Quick/Quick) to version [4.0.0](https://github.com/Quick/Quick/releases/tag/v4.0.0), and fixes a Xcode 13 warning.

Updated dependencies

---

Cartfile.private
Cartfile.resolved
Package.swift

This PR bumps Quick to v5.0.1. and Nimble to v10.0.0 to fix an issue with Xcode 13.3: https://github.com/Quick/Quick/issues/1123

Bump Quick and Nimble

---

SimpleKeychain/A0SimpleKeychain+KeyPair.h
SimpleKeychain/A0SimpleKeychain+KeyPair.m
SimpleKeychain/A0SimpleKeychain.h
SimpleKeychain/A0SimpleKeychain.m
SimpleKeychain/SimpleKeychain.h
SimpleKeychainApp/AppDelegate.swift
SimpleKeychainTests/SimpleKeychainSpec.swift
tvOSTestHost/AppDelegate.swift
tvOSTestHost/ViewController.swift

This PR removes the license header from all source files, including the test files.
This was done for Auth0.swift v2: https://github.com/auth0/Auth0.swift/pull/537

Remove license header from source files [SDK-3389]

---

LICENSE

This PR updates the year in the `LICENSE` file to 2022 and adds the company email and website, to match the `LICENSE` file of Auth0.swift: https://github.com/auth0/Auth0.swift/blob/master/LICENSE

Update year in license file

---

Package.swift
SimpleKeychain.podspec
SimpleKeychain.xcodeproj/project.pbxproj
SimpleKeychain/A0SimpleKeychain.h
SimpleKeychain/A0SimpleKeychain.m
V1_MIGRATION_GUIDE.md

⚠️ **THIS PR CONTAINS BREAKING CHANGES**
This PR raises the deployment targets to:
- iOS **12.0**
- macOS **10.15**
- tvOS **12.0**
- watchOS **6.2**
Also preprocessor macros regarding older platform versions were removed, as well as some blocks of code that worked around limitations on those older versions.

Drop old platform versions [SDK-3387]

---

README.md

This PR updates the README after the Auth0.swift one, and adds **First Availability** labeling plus a disclaimer.

Update README [SDK-3416]

---

SimpleKeychain/A0SimpleKeychain+KeyPair.h
SimpleKeychain/A0SimpleKeychain+KeyPair.m
V1_MIGRATION_GUIDE.md

⚠️ **THIS PR CONTAINS BREAKING CHANGES**
This PR removes the deprecated method `publicRSAKeyData(forTag:)`.

Remove deprecated method [SDK-3413]

---

SimpleKeychain/A0SimpleKeychain.h
SimpleKeychain/A0SimpleKeychain.m
V1_MIGRATION_GUIDE.md

⚠️ **THIS PR CONTAINS BREAKING CHANGES**
This PR removes the usage of the following deprecated iOS/macOS/tvOS/watchOS properties:
- `kSecAttrAccessibleAlways`: https://developer.apple.com/documentation/security/ksecattraccessiblealways
- `kSecAttrAccessibleAlwaysThisDeviceOnly`: https://developer.apple.com/documentation/security/ksecattraccessiblealwaysthisdeviceonly
This results in the removal of the following cases of the `A0SimpleKeychainItemAccessible` enum:
- `A0SimpleKeychainItemAccessibleAlways`
- `A0SimpleKeychainItemAccessibleAlwaysThisDeviceOnly`
[X] I have read the [Auth0 general contribution …

Remove usage of deprecated properties [SDK-3414]

---

Package.swift
SimpleKeychain.podspec
V1_MIGRATION_GUIDE.md

⚠️ **THIS PR CONTAINS BREAKING CHANGES**
The minimum Swift version supported was raised to 5.5.
https://developer.apple.com/news/?id=2t1chhp3

Drop support for old Swift versions [SDK-3444]

---

.gitignore
.shiprc
Gemfile.lock
fastlane/Fastfile
fastlane/README.md

This PR adds API documentation generation using DocC. The documentation itself will be committed as a seperate PR, for reviewability sake.
See internal ticket SDK-3450
Please describe how this can be tested by reviewers. Be specific about anything not tested and reasons why. If helpful, please include manual testing steps as well.

[SDK-3450] API Documentation Generation

---

fastlane/Fastfile

This PR updates the API docs generation lane by deleting the docs directory before generating new docs, and adds an `index.html` to the docs root that redirects to `/documentation/simplekeychain/`.

Improve API docs generation

---

README.md
SimpleKeychain/SimpleKeychain.swift
SimpleKeychain/SimpleKeychainError.swift
SimpleKeychainTests/SimpleKeychainSpec.swift
V1_MIGRATION_GUIDE.md

This PR adds support for specifying custom attributes to be added to all queries. This lends greater flexibility to the library, enabling it to handle a wider set of use cases.

Add support for custom attributes

---

.circleci/config.yml
SimpleKeychain.xcodeproj/project.pbxproj
SimpleKeychain.xcodeproj/xcshareddata/xcschemes/SimpleKeychain-macOS.xcscheme

This PR updates the naming of schemes and targets, replacing OSX with macOS.

Replace OSX with macOS in schemes and targets

---

SimpleKeychain.podspec

This PR adds `-fa` to the Podspec version number.

Add fa to Podspec version

---

README.md
SimpleKeychain.podspec
SimpleKeychain/SimpleKeychain.swift

This PR changes 'Access Group' to 'access group' in the README, API docs, and Podfile description to match the way it's used in the [Apple docs](https://developer.apple.com/documentation/security/keychain_services/keychain_items/sharing_access_to_keychain_items_among_a_collection_of_apps).

Fix 'access group' capitalization

---

.circleci/config.yml
Gemfile
Gemfile.lock

This PR updates the CI config to use the Codecov orb instead of the bash uploader.

Use Codecov orb

---

SimpleKeychain/SimpleKeychain.swift
SimpleKeychainTests/SimpleKeychainSpec.swift

- N/A All new/changed/fixed functionality is covered by tests (or N/A)
- N/A I have added documentation for all new/changed functionality (or N/A)
With this PR, SimpleKeychain does not only validate whether `LocalAuthentication` could be imported but also whether the target OS is not tvOS.
Without this check, compilation for tvOS fails with Xcode 14 (14A309) as `LocalAuthentication` seems to be importable even though `LAContext` is not available:

Fix Xcode 14 tvOS builds

---

SimpleKeychainTests/SimpleKeychainSpec.swift

This PR disambiguates the `Predicate` type used in the custom matchers to use [Nimble's](https://github.com/Quick/Nimble) `Predicate` instead of the [newly introduced type](https://developer.apple.com/documentation/foundation/predicate) in Swift 5.9.

Update unit tests to compile with Xcode 15

---

CONTRIBUTING.md
EXAMPLES.md
README.md

This PR updates all the Markdown documentation to use the new admonitions syntax supported by GitHub. The previous syntax is not supported anymore.

Use the new syntax for Markdown admonitions

---

README.md

The **Support Policy** section of the README includes a bit that states the initial versions from which the "last 4 major versions" policy will apply.
This bit [was recently removed](https://github.com/auth0/Auth0.swift/pull/808) from Auth0.swift's README because it resulted in confusion regarding the currently supported platform versions.
This PR removes it from SimpleKeychain's README as well, and updates the versions in the **Requirements** section.

Update Platforms Support Policy in README

---

.github/actions/setup/action.yml
.github/workflows/main.yml

* upgraded ruby/setup-ruby action from version v1.152.0 to v1.178.0 to support ruby version `3.0.7`
https://github.com/auth0/SimpleKeychain/actions/runs/9581919093/job/26419770960

ci: upgraded ruby/setup-ruby action from version v1.152.0 to v1.178.0

---

.github/actions/test/action.yml
CONTRIBUTING.md
Cartfile.private
Cartfile.resolved
Package.swift
SimpleKeychain.xcodeproj/project.pbxproj
SimpleKeychainTests/AccessibilitySpec.swift
SimpleKeychainTests/SimpleKeychainErrorSpec.swift
SimpleKeychainTests/SimpleKeychainSpec.swift

* Migrated from `Quick` & `Nimble` for unit tests in this package to use XCTest to remove dependency on third party packages
* All the unit tests are successfully passing on all the platforms

test: migrated from Quick & Nimble to use XCTest to remove dependency on third party packages

---

Package.swift
README.md
SimpleKeychain.podspec
SimpleKeychain.xcodeproj/project.pbxproj

* Dropped support for Xcode 14 as its no longer supports apps built with it to be uploaded to Appstore. 
* Dropped support for Swift versions 5.7 & 5.8 as they came in along with Xcode 14 which we are no longer supporting. 
* Updated the support policy to be more explicit on when we start dropping support for any platform versions, accordingly dropped support for iOS 13 & tvOS 13.

chore: dropped support for xcode 14, swift version 5.7, 5.8, iOS 13 & tvOS 13

---

.github/workflows/main.yml
Package.swift
README.md
SimpleKeychain.podspec
SimpleKeychain.xcodeproj/project.pbxproj

Xcode version to 16.1 in CI
Swift versions upgrades in Package.swift , SimpleKeychain.podspec and Readme.md

Upgrades Xcode version to 16 in CI 
